### ISSUE TITLE
Indices go from 1..n to 0..n after a re-order

### ISSUE THREAD

**Issue by Ommy** [SanaMobile/sana.protocol_builder#135]
On current master, when I create two elements like this:

![screen shot 2015-06-19 at 7 59 04 pm](https://cloud.githubusercontent.com/assets/978947/8265026/cff86968-16bd-11e5-9668-1849d270b946.png)

And then move the first one to the top, I end up with this:

![screen shot 2015-06-19 at 7 59 15 pm](https://cloud.githubusercontent.com/assets/978947/8265027/db9ac892-16bd-11e5-978a-54aca1479843.png)

Why does it start at 1-based index, and then switches to 0-based?

**Comment by Trinovantes** [comment]
That's the display index (https://github.com/SanaMobile/sana.protocol_builder/blob/master/src-frontend/app/templates/components/page-list.hbs#L7)

I'm not exactly sure why it starts off at 1.

@ConnorCimowsky should know more about this.

**Comment by Ommy** [comment]
This seems to have been fixed. Closing.

**Comment by ConnorCimowsky** [comment]
I think we fixed this? @Ommy
