### ISSUE TITLE
Create element/page/procedure should first check if server returned 200 before updating UI

### ISSUE THREAD

**Issue by Trinovantes** [SanaMobile/sana.protocol_builder#145]
If the server does not return a 200 when trying to create a new element/page/procedure, the UI still updates with a new component with id of null. It should instead show a loading spinner and wait for a server response before updating the UI.

**Comment by Ommy** [comment]
Should we complete #123 before this? Or else this will look weird with no updates on the frontend without any indication that something bad happened

**Comment by Trinovantes** [comment]
No longer using Ember so I'm not sure if this is relevant anymore.
