### ISSUE TITLE
Add logout support

### ISSUE THREAD

**Issue by ConnorCimowsky** [SanaMobile/sana.protocol_builder#151]

**Comment by Trinovantes** [comment]
Should just be an endpoint that deletes the user's token

**Comment by ConnorCimowsky** [comment]
Yup. `DELETE /tokens/abc123` or something?

**Comment by Trinovantes** [comment]
I'd rather just use  `POST /logout` so we're not coupled with how our authentication works

**Comment by ConnorCimowsky** [comment]
:100:
