### ISSUE TITLE
Element types should be returned by the server to clients

### ISSUE THREAD

**Issue by Kapin** [SanaMobile/sana.protocol_builder#163]
More of a nice to have but essentially, we should have the server return the format of elements and their types down the road to clients. This will make validations easier and more extendible.

This is not a priority.

**Comment by Trinovantes** [comment]
What do you by "format"?

**Comment by Kapin** [comment]
e.g. an ENTRY element contains X properties of Y types or if we had a new element type it would specify what properties (of all element properties) it would take (so ENTRY does not have choices, but SELECT does).

**Comment by Trinovantes** [comment]
Since the current front-end client shows an icon representing each element type, I don't think it's feasible anymore to let the server decide what types are available. Otherwise, we will need to dynamically edit the CSS/images being loaded.
