### ISSUE TITLE
Pages should display a preview of what is inside them.

### ISSUE THREAD

**Issue by Kapin** [SanaMobile/sana.protocol_builder#197]

**Comment by Trinovantes** [comment]
![2015-07-20 12 50 09](https://cloud.githubusercontent.com/assets/458691/8781598/01b04a24-2ede-11e5-958b-acaf8056ce98.jpg)

Possible design to support multiple elements. Bottom bar is a list of buttons and icons for creating the different types of elements e.g. multi-select, single-select, etc.
