### ISSUE TITLE
Port frontend to Backbone

### ISSUE THREAD

**Issue by Trinovantes** [SanaMobile/sana.protocol_builder#208]
Each of these will be in a separate PR
- [x] Setup boilerplate for basic SPA with Backbone, Coffeescript, RequireJS, Grunt, Less
- [x] Setup authentication
- [ ] Port document creation
- [ ] Port page creation
- [ ] Port element creation

**Comment by ConnorCimowsky** [comment]
📢 STEP AWAY FROM THE REQUIREJS 📢

**Comment by Trinovantes** [comment]
Then I suggest you find another way to deal with dependencies.

**Comment by Trinovantes** [comment]
I'm currently looking into gulp and browserify to see if it's simpler to config

**Comment by Ommy** [comment]
I've heard good things about using Marionette for Backbone views.

**Comment by Trinovantes** [comment]
I'm planning to use Marionette too. It's too much of a hassle trying to debug raw Backbone zombie views

**Comment by Trinovantes** [comment]
Going to turn this into a milestone instead
