### ISSUE TITLE
/api/procedures return page id instead of page contents

### ISSUE THREAD

**Issue by Trinovantes** [SanaMobile/sana.protocol_builder#256]
e.g. When I make a request to `localhost:8000/api/procedures/100`, I get:
```
{
  "id": 100,
  "title": "Untitled Procedure 2",
  "author": "Stephen",
  "version": null,
  "uuid": null,
  "owner": 3,
  "pages": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
  ],
  "last_modified": "2015-12-06T23:47:15.317210Z",
  "created": "2015-12-06T21:50:40.178327Z"
}
```

If the page id is specified, it should transmit the page contents instead of just the primary keys. 

Note that if the page is not specified (`/api/procedures`), then we can discard the `pages` attribute since it's not needed (alternatively, make it optional via a flag e.g. `?return_page_contents=true`)

**Comment by Ommy** [comment]
If the procedure ID is not specified, `/api/procedures`, then we don't want pages to be returned, but if a specific procedure is required, i.e. `/api/procedures/10`, then return page contents?

**Comment by Trinovantes** [comment]
Yes
