### ISSUE TITLE
Tests with initialize_permissions decorator don't run

### ISSUE THREAD

**Issue by Ommy** [SanaMobile/sana.protocol_builder#261]
The tests that have the `@initialize_permissions` decorator don't seem to be run when calling `./manage.py test`. I got around it by putting the method call to `#initialize_permissions` within the `#setUp` method. Maybe there's a nicer way, but we need to get this fixed up for the Pages tests.

**Comment by Trinovantes** [comment]
I think it makes sense to initialize the permissions inside `setUp` since it's supposed to "set up" our tests

**Comment by Ommy** [comment]
Yeah I agree, but I think if we put it in `#setUp` then we need to create the users in that method as well as opposed to in the test itself.
