### ISSUE TITLE
Sana should escape quotes when generating XML file

### ISSUE THREAD

**Issue by Ommy** [SanaMobile/sana.protocol_builder#293]
```
<Procedure author=""blah" title="test">
</Procedure>
```

**Comment by Ommy** [comment]
Unnoticed, already does this.

**Comment by Trinovantes** [comment]
What do you mean? Didn't we get that invalid xml last week?

**Comment by Trinovantes** [comment]
This should be covered in a test. Make sure other xml libraries can parse it properly

**Comment by Ommy** [comment]
I was testing again with a clean branch and noticed that quotes are already escaped. I'll write a test or two for it but yeah functionality exists.

**Comment by Trinovantes** [comment]
@Ommy or @Kapin can you write some tests to close this?
