### ISSUE TITLE
Implement Conditional Logic on frontend

### ISSUE THREAD

**Issue by Trinovantes** [SanaMobile/sana.protocol_builder#321]
- [x] Allow expanding criteria to logical list
- [x] Allow contracting logical list to criteria
- [x] Allow deleting criteria
- [x] Allow deleting logical list
- [x] Deleting last criteria disables condition editor
- [ ] Highlight pages in sidebar containing operand elements
- [ ] Show preview of condition in page list
- [x] Allow adding criteria to list
- [ ] Auto-complete for elements
- [ ] Auto-complete for value (if element is a choice-based element)
- [ ] First page should have no options to create conditional logic
- [ ] If page is moved to first page, condition should be removed

**Comment by Kapin** [comment]
Can you make sure this is done in chunks and not one massive commit. It is literally going to be impossible to review a 100+ file change (or something like that).

**Comment by Trinovantes** [comment]
Going to make the last 5 parts individual enhancements
