### ISSUE TITLE
Redirect to base procedure editor if page in URL is invalid

### ISSUE THREAD

**Issue by Trinovantes** [SanaMobile/sana.protocol_builder#335]
e.g. URL is `/procedures/28/page/123` but Page 123 doesn't exist. Then the front end should just redirect to `/procedures/28`

**Comment by Kapin** [comment]
This should replace the 404 page. @Trinovantes I literally have no idea where this goes. Assigning to you.

**Comment by Trinovantes** [comment]
This is a minor issue with no adverse effect. Just mark it as won't fix
