### ISSUE TITLE
Server cannot recognize newlines in answers

### ISSUE THREAD

**Issue by Trinovantes** [SanaMobile/sana.protocol_builder#360]
Request
```
answer: "a↵a"
choices: ["a", "a↵a"]
concept: null
display_index: 0
element_type: "SELECT"
id: 111
page: 37
required: false
```

Response:
```
{non_field_errors: ["Answer must be one of the choices"]}
non_field_errors: ["Answer must be one of the choices"]
```

**Comment by Kapin** [comment]
Two issues going on here. There is a bug in element.js where a choice element isn't clearing the answer properly. Second one I can look into but am having a lot of trouble reproducing right now.

**Comment by Trinovantes** [comment]
First issue is already fixed in my branch
