### ISSUE TITLE
Document the front-end

### ISSUE THREAD

**Issue by Kapin** [SanaMobile/sana.protocol_builder#390]
We need documentation on how everything works and need to clarify the setup/running instructions.

**Comment by Trinovantes** [comment]
The code is already self-documenting (I'm not going to write a tutorial on how Backbone works if that's what you meant) and I've included inline explanations for design decisions

For setup/running, it's already in the README

**Comment by Kapin** [comment]
I was discussing the folder structure, how to add additional languages, how to edit the config properly, etc.

Things that are not obvious to someone who did not build this but has backbone experience.
