### ISSUE TITLE
A long value in a criteria is hard to read

### ISSUE THREAD

**Issue by Kapin** [SanaMobile/sana.protocol_builder#395]
<img width="183" alt="screen shot 2016-03-06 at 3 18 28 pm" src="https://cloud.githubusercontent.com/assets/995382/13556714/b86b18e0-e3ae-11e5-92c2-3ae7ebfc6708.png">

The answer could be long, it should be apparent what is entered.

**Comment by Trinovantes** [comment]
Get a bigger screen? There's literally nothing I can do about this

**Comment by Kapin** [comment]
You can't assume everyone has a 24 inch high resolution monitor.
