### ISSUE TITLE
Create Document model

### ISSUE THREAD

**Issue by Trinovantes** [SanaMobile/sana.protocol_builder#45]
This model should encompass a single "sana protocol" with all the pages, boolean logic, and elements. 

Maybe we should plan out the entire model and its relationships so we can avoid migrating our database on every commit? @ConnorCimowsky @Kapin

**Comment by ConnorCimowsky** [comment]
Sounds good. Happy to chat whenever possible!

**Comment by Trinovantes** [comment]
Closed #67
