### ISSUE TITLE
Consider writing a parser to make testing easier

### ISSUE THREAD

**Issue by Kapin** [SanaMobile/sana.protocol_builder#49]
It doesn't look all that hard. If we can build the model ourselves, parsing one should validate it isn't broken.

https://docs.python.org/2/library/xml.etree.elementtree.html#parsing-xml

**Comment by Trinovantes** [comment]
Do you mean parsing a sana doc or parsing xml in general?

**Comment by Kapin** [comment]
parsing a sana doc, which in itself is similar to xml.

**Comment by Trinovantes** [comment]
Can you give an example of a possible use case?

**Comment by Kapin** [comment]
Makes verification wayyyy easier. We can parse a protocol (test that this works first) and then ensure that what the generator outputs is what was inputted (with some tweaks).

It's more of a P2 but we should be able to reverse anything we generate easily.

**Comment by Trinovantes** [comment]
I'm assuming we don't have time to implement this feature.
